### ISSUE TITLE
Cannot be loaded with Glide

### ISSUE THREAD

**Issue by marczahn** [airbrake/gobrake#38]
Hi,

We are using this library and basically it works fine and as expected. But we have a problem related to Glide.

When I do a glide install I often get the error

>  Failed to set version on gopkg.in/airbrake/gobrake.v2 to d63ed4454f4c5abcb02b189fdf5cfec9baaae752: Unable to update checked out version

I don't know what this is related to. My glide.yml:

```
import:
- package: github.com/mitchellh/go-homedir
- package: github.com/spf13/cobra
- package: github.com/spf13/viper
  version: ^1.0.0
- package: github.com/gin-gonic/gin
  version: ^1.2.0
- package: github.com/gin-contrib/sse
- package: github.com/golang/protobuf
  subpackages:
  - proto
- package: github.com/mattn/go-isatty
  version: ^0.0.2
- package: github.com/gin-gonic/contrib
- package: github.com/dgrijalva/jwt-go
  version: ^3.0.0
  subpackages:
  - request
- package: github.com/dimiro1/health
- package: github.com/gocraft/dbr
  version: ^2.1.0
- package: github.com/pressly/goose
  version: ^2.1.0
- package: github.com/lib/pq
- package: github.com/airbrake/gobrake
  version: ^3.0.3
```
glide.lock:
```
hash: 79447dcb9523201b12266895651e6fabb02439d66260b65deed26ce778c34338
updated: 2017-09-05T15:32:41.423703519+02:00
imports:
- name: github.com/airbrake/gobrake
  version: d63ed4454f4c5abcb02b189fdf5cfec9baaae752
- name: github.com/dgrijalva/jwt-go
  version: d2709f9f1f31ebcda9651b03077758c1f3a0018c
  subpackages:
  - request
- name: github.com/dimiro1/health
  version: 22672c48855646f5d54b6315336d2e3fee6eef81
- name: github.com/fsnotify/fsnotify
  version: 4da3e2cfbabc9f751898f250b49f2439785783a1
- name: github.com/gin-contrib/cors
  version: cf4846e6a636a76237a28d9286f163c132e841bc
- name: github.com/gin-contrib/sse
  version: 22d885f9ecc78bf4ee5d72b937e4bbcdc58e8cae
- name: github.com/gin-gonic/contrib
  version: 0f937ce6d016f44b2f5b1f03787e055977e7c0b8
  subpackages:
  - jwt
- name: github.com/gin-gonic/gin
  version: d459835d2b077e44f7c9b453505ee29881d5d12d
  subpackages:
  - binding
  - render
- name: github.com/gocraft/dbr
  version: b2f0ffcef2a64c0729d5818e103bc019caed7b22
  subpackages:
  - dialect
- name: github.com/golang/protobuf
  version: ab9f9a6dab164b7d1246e0e688b0ab7b94d8553e
  subpackages:
  - proto
- name: github.com/hashicorp/hcl
  version: 8f6b1344a92ff8877cf24a5de9177bf7d0a2a187
  subpackages:
  - hcl/ast
  - hcl/parser
  - hcl/scanner
  - hcl/strconv
  - hcl/token
  - json/parser
  - json/scanner
  - json/token
- name: github.com/inconshreveable/mousetrap
  version: 76626ae9c91c4f2a10f34cad8ce83ea42c93bb75
- name: github.com/lib/pq
  version: e42267488fe361b9dc034be7a6bffef5b195bceb
- name: github.com/magiconair/properties
  version: be5ece7dd465ab0765a9682137865547526d1dfb
- name: github.com/mattn/go-isatty
  version: fc9e8d8ef48496124e79ae0df75490096eccf6fe
- name: github.com/mitchellh/go-homedir
  version: b8bc1bf767474819792c23f32d8286a45736f1c6
- name: github.com/mitchellh/mapstructure
  version: d0303fe809921458f417bcf828397a65db30a7e4
- name: github.com/pelletier/go-toml
  version: 9c1b4e331f1e3d98e72600677699fbe212cd6d16
- name: github.com/pkg/errors
  version: 645ef00459ed84a119197bfb8d8205042c6df63d
- name: github.com/pressly/goose
  version: 056a4d47dcc4d67fa3947a4f13945a5c690e568b
- name: github.com/satori/go.uuid
  version: 879c5887cd475cd7864858769793b2ceb0d44feb
- name: github.com/sirupsen/logrus
  version: ba1b36c82c5e05c4f912a88eab0dcd91a171688f
- name: github.com/spf13/afero
  version: 36f8810e2e3d7eeac4ac05b57f65690fbfba62a2
  subpackages:
  - mem
- name: github.com/spf13/cast
  version: acbeb36b902d72a7a4c18e8f3241075e7ab763e4
- name: github.com/spf13/cobra
  version: 2df9a531813370438a4d79bfc33e21f58063ed87
- name: github.com/spf13/jwalterweatherman
  version: 0efa5202c04663c757d84f90f5219c1250baf94f
- name: github.com/spf13/pflag
  version: e57e3eeb33f795204c1ca35f56c44f83227c6e66
- name: github.com/spf13/viper
  version: 25b30aa063fc18e48662b86996252eabdcf2f0c7
- name: github.com/ugorji/go
  version: 8c0409fcbb70099c748d71f714529204975f6c3f
  subpackages:
  - codec
- name: golang.org/x/sys
  version: ab9e364efd8b52800ff7ee48a9ffba4e0ed78dfb
  subpackages:
  - unix
- name: golang.org/x/text
  version: 18c65dde6afd36dbc39197ca72008895b8dfbfb6
  subpackages:
  - transform
  - unicode/norm
- name: gopkg.in/airbrake/gobrake.v2
  version: d63ed4454f4c5abcb02b189fdf5cfec9baaae752
- name: gopkg.in/go-playground/validator.v8
  version: 5f1438d3fca68893a817e4a66806cea46a9e4ebf
- name: gopkg.in/yaml.v2
  version: eb3733d160e74a9c7e442f435eb3bea458e1d19f
testImports: []
```
